### ISSUE TITLE
Issue when running after setting up Babel/ES6

### ISSUE THREAD

**Issue by kambanwait** [ShMcK/WebpackAngularDemos#8]
Getting the following issues when trying to run `npm start` 

Tried copying your source code in to mine and checked that it's the same but still get the same issue. Is this tried to use an older version of `"babel-loader": "^5.3.1",` too after seeing someone else have the same issue but no joy.

Can you help?

```
~/kam.dev/kam/mcoAngularPOC $ npm start

> mcoAngularProofofConcept@1.0.0 start /Users/KamBanwait/kam.dev/kam/mcoAngularPOC
> webpack-dev-server --content-base app --hot

http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/KamBanwait/kam.dev/kam/mcoAngularPOC/app
webpack: wait until bundle finished: /
Hash: 62b04a08f3a06eaba7c3
Version: webpack 1.12.9
Time: 1683ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.13 MB       0  [emitted]  app
chunk    {0} bundle.js (app) 1.08 MB [rendered]
    [0] multi app 40 bytes {0} [built]
    [1] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
    [2] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]
    [3] ./app/core/bootstrap.js 272 bytes {0} [built] [1 warning] [1 error]
    [4] ./app/core/vendor.js 117 bytes {0} [built]
    [5] ./app/index.scss 1.03 kB {0} [built]
    [6] ./~/css-loader!./~/sass-loader!./app/index.scss 212 bytes {0} [built]
    [7] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
    [8] ./~/style-loader/addStyles.js 7.21 kB {0} [built]
    [9] ./~/angular/index.js 48 bytes {0} [built]
   [10] ./~/angular/angular.js 1.07 MB {0} [built]

WARNING in ./app/core/bootstrap.js
jshint results in errors
  'angular' is not defined. @ line 9 char 1
    angular.element(document).ready(function () {

  'document' is not defined. @ line 9 char 17
    angular.element(document).ready(function () {

  'angular' is not defined. @ line 10 char 3
      angular.bootstrap(document, [appModule.name], {

  'document' is not defined. @ line 10 char 21
      angular.bootstrap(document, [appModule.name], {

WARNING in ./app/index.js
jshint results in errors
  Use the function form of "use strict". @ line 1 char 1
    'use strict';

  'default parameters' is only available in ES6 (use esnext option). @ line 6 char 30
    function printMessage (status='working') {

  'let' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz). @ line 8 char 5
        let message = 'ES6';

  Unexpected '`'. @ line 10 char 17
        console.log(`${message} is ${status}`);

  Expected an identifier and instead saw '}'. @ line 11 char 1
    }

  Expected ')' and instead saw 'printMessage'. @ line 12 char 1
    printMessage();

  Unmatched '{'. @ line 6 char 42
    function printMessage (status='working') {

  Unrecoverable syntax error. (100% scanned). @ line 12 char undefined
    undefined

ERROR in ./app/index.js
Module build failed: Error: StringMap expected string key
    at stringmap.set (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/stringmap/stringmap.js:99:19)
    at Scope.add (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scope.js:102:17)
    at /Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scopetools.js:65:25
    at Array.forEach (native)
    at createScopes (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scopetools.js:64:21)
    at visit (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:25:19)
    at visit (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:43:25)
    at traverse (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:56:5)
    at Object.setupScopeAndReferences (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scopetools.js:18:5)
    at ngAnnotate (/Users/KamBanwait/kam.dev/kam/mcoAngularPOC/node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/ng-annotate-main.js:1055:16)
 @ ./app/core/bootstrap.js 8:16-35
```

**Comment by ShMcK** [comment]
Looks like the `ng-annotate-loader` may be the culprit. Basically what ng-annotate does is prevent your dependency names from being renamed during minification (for example, ensuring "dependency1" won't become shortened to something unrecognizable like "d". Perhaps you could trying using the [`ng-annotate-webpack-plugin`](https://www.npmjs.com/package/ng-annotate-webpack-plugin) as an alternative?

Unfortunately, the wifi where I'm at now on vacation is too poor to install npm packages. I can't really test if this is really the cause, but I'll get back to you.

**Comment by kambanwait** [comment]
Thanks for the suggestion. Will try removing it and swapping it out with annotate-webpack-plugin. Will keep you updated - enjoy the vacation!

**Comment by kambanwait** [comment]
Just tried it. Didn't 'work'. Following Part 1 it should say Angular is 'true' but it just shows the actual Angular code instead.

I've removed the annotate-webpack-plugin and commented out the ES6 code and it works fine.

Not sure if I'm adding the annotate-webpack-plugin correctly as it was giving me errors when I just replaced it in webpack.config so I used it via the "usage" section on it's npm page and it still didn't work

Looks like function `printMessage (status='working')`  is causing Angular to not render correctly. Removing this works - which makes sense seeing as ES6 is no longer supported?

**Comment by matewilk** [comment]
+1

I'm also experiencing the same issue here. Any solution ?

Edit:

I've found on the tutorial [page](http://www.shmck.com/webpack-angular-part-1/)  a [solution](https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53#.doc5xyfcg)

Basically it is related to Babel 6 presets.

**Comment by ShMcK** [comment]
Yes, it seems Babel 5 -> 6 now requires you to specify which preset you're using.

`npm install --save-dev babel-preset-es2015`

/webpack.config.js

``` js
    {
      test: /\.js$/,
      loader: 'ng-annotate!babel?presets[]=es2015!jshint'
    }
```

If that solves the issue for you, let me know and I'll update the tutorial.

**Comment by matewilk** [comment]
I'm new to webpack so my loader config looks like this: 

``` javascript
            {
                test: /\.js$/,
                loader: 'ng-annotate!babel!jshint',
                exclude: /node_modules|bower_components/
            },
            {
                test: /\.js$/,
                loader: 'babel',
                query: {
                    // https://github.com/babel/babel-loader#options
                    cacheDirectory: true,
                    presets: ['es2015', 'stage-2']
                },
                exclude: /node_modules|bower_components/
            }
```

And it's working fine, but I've just noticed that I have duplication of `babel` in both loaders so probably your solution is the way to go.

**Comment by ShMcK** [comment]
Everything should be working now. Thanks for the feedback :)

**Comment by bpj101** [comment]
I discovered when using the jshint-loader, you have to have at least an empty object "{}" in the .jshintrc file.
